### ISSUE TITLE
Undefined Reference Error

### ISSUE THREAD

**Issue by TechAspirant** [codepr/sol#3]
Hello,

On make I am getting error as below
~/Desktop/mqttbroker/sol-master$ make
[ 59%] Building C object CMakeFiles/sol.dir/src/pack.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/bst.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/hashtable.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/util.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/list.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/sol.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/mqtt.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/core.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/network.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/trie.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/iterator.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/config.c.o
[ 59%] Building C object CMakeFiles/sol.dir/src/server.c.o
Linking C executable sol
CMakeFiles/sol.dir/src/util.c.o: In function `generate_uuid':
util.c:(.text+0x58c): undefined reference to `uuid_generate_random'
util.c:(.text+0x597): undefined reference to `uuid_unparse'
collect2: error: ld returned 1 exit status
make[2]: *** [sol] Error 1
make[1]: *** [CMakeFiles/sol.dir/all] Error 2
make: *** [all] Error 2

I have checked uuid-dev is installed

**Comment by codepr** [comment]
I suppose you're running Ubuntu. What gcc version?

**Comment by TechAspirant** [comment]
Yes Ubuntu 14.04 LTS 64 bit  and GCC Version 4.8.4

**Comment by TechAspirant** [comment]
Now, I am able to successfully compile all the files and able to start the broker.
I want to know is there any possibility of setting username and password for the broker.

**Comment by codepr** [comment]
Username and password are correctly deserialized on packet reception but currently are ignored in the server side. Planning on adding support for authentication.
