### ISSUE TITLE
Many data races when use `-fsanitize=thread`

### ISSUE THREAD

**Issue by hongliang5316** [codepr/sol#7]
Hi,
i just change follow in `CMakeLists.txt`
```
-    -Wno-unused-result -std=c11 -ggdb -fsanitize=address \
+    -Wno-unused-result -std=c11 -ggdb -fsanitize=thread \
```
==================
WARNING: ThreadSanitizer: data race (pid=1015)
  Read of size 8 at 0x00000049b5a8 by thread T2:
    #0 xmalloc /sol/src/util.c:198 (sol+0x45b8e7)
    #1 ev_api_init /sol/src/ev.c:106 (sol+0x4105b7)
    #2 ev_init /sol/src/ev.c:634 (sol+0x412438)
    #3 eventloop_start /sol/src/server.c:907 (sol+0x44b5cd)
    #4 <null> <null> (libtsan.so.0+0x2cb4d)

  Previous write of size 8 at 0x00000049b5a8 by thread T1:
    #0 xmalloc /sol/src/util.c:198 (sol+0x45b903)
    #1 ev_api_init /sol/src/ev.c:106 (sol+0x4105b7)
    #2 ev_init /sol/src/ev.c:634 (sol+0x412438)
    #3 eventloop_start /sol/src/server.c:907 (sol+0x44b5cd)
    #4 <null> <null> (libtsan.so.0+0x2cb4d)

  Location is global 'memory' of size 8 at 0x00000049b5a8 (sol+0x00000049b5a8)

  Thread T2 (tid=1018, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2ee2b)
    #1 start_server /sol/src/server.c:993 (sol+0x44c111)
    #2 main /sol/src/sol.c:126 (sol+0x457f54)

  Thread T1 (tid=1017, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x2ee2b)
    #1 start_server /sol/src/server.c:993 (sol+0x44c111)
    #2 main /sol/src/sol.c:126 (sol+0x457f54)

SUMMARY: ThreadSanitizer: data race /sol/src/util.c:198 in xmalloc
==================

**Comment by codepr** [comment]
I didn't know that sanitizer, it's great. It highlighted some obvious fixes. Thank you very much!
